pipeline:
  name: getdeps_mac
  identifier: getdeps_mac
  projectIdentifier: DhrubaCI
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: dhrubaaccountconnector
        repoName: proxygen
        build: <+input>
  stages:
    - stage:
        name: stage
        identifier: stage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Fetch step
                  identifier: Fetch_ninja
                  spec:
                    shell: Sh
                    command: python3 build/fbcode_builder/getdeps.py fetch --no-tests <+repeat.item>
                  failureStrategies: []
                  strategy:
                    repeat:
                      items:
                        - ninja
                        - cmake
                        - zlib
                        - zstd
                        - boost
                        - double-conversion
                        - fmt
                        - gflags
                        - glog
                        - googletest
                        - lz4
                        - openssl
                        - snappy
                        - libevent
                        - autoconf
                        - automake
                        - libtool
                        - gperf
                        - libsodium
                        - xz
                        - folly
                        - fizz
                        - mvfst
                        - wangle
                    maxConcurrency: 24
              - step:
                  type: Run
                  name: Build step
                  identifier: Build_step
                  spec:
                    shell: Sh
                    command: python3 build/fbcode_builder/getdeps.py fetch --no-tests <+repeat.item>
                  failureStrategies: []
                  strategy:
                    repeat:
                      items:
                        - ninja
                        - cmake
                        - zlib
                        - zstd
                        - boost
                        - double-conversion
                        - fmt
                        - gflags
                        - glog
                        - googletest
                        - lz4
                        - openssl
                        - snappy
                        - libevent
                        - autoconf
                        - automake
                        - libtool
                        - gperf
                        - libsodium
                        - xz
                        - folly
                        - fizz
                        - mvfst
                        - wangle
                    maxConcurrency: 2
              - step:
                  type: Run
                  name: Build proxygen
                  identifier: Build_proxygen
                  spec:
                    shell: Sh
                    command: python3 build/fbcode_builder/getdeps.py build --src-dir=. proxygen  --project-install-prefix proxygen:/usr/local
  variables:
    - name: fetchstep
      type: String
      description: ""
      value: <+input>
